'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/ContextProvider";
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from '@mui/material';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import { theme } from "@/theme";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const basename = 'http://localhost:3000';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {/* strudel-kit-variable-next-line */}
            <AppProvider appTitle="Demo App">
              {children}  
            </AppProvider>
          </ThemeProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}
